// Mock data — will be replaced by API call: GET /api/public/hospitals
export const HOSPITALS = [
  {
    id: 1,
    name: "North Bengal Medical Centre",
    city: "Siliguri",
    state: "West Bengal",
    type: "Multi-Specialty Hospital",
    beds: 450,
    established: 1998,
    departments: 18,
  },
  {
    id: 2,
    name: "Jalpaiguri Care Hospital",
    city: "Jalpaiguri",
    state: "West Bengal",
    type: "General Hospital",
    beds: 180,
    established: 2005,
    departments: 9,
  },
  {
    id: 3,
    name: "MedLife Hospital",
    city: "Kolkata",
    state: "West Bengal",
    type: "Multi-Specialty Hospital",
    beds: 320,
    established: 2010,
    departments: 14,
  },
  {
    id: 4,
    name: "City Health Institute",
    city: "Siliguri",
    state: "West Bengal",
    type: "Specialized Hospital",
    beds: 220,
    established: 2015,
    departments: 11,
  },
  {
    id: 5,
    name: "Apollo Spectra Hospital",
    city: "Bengaluru",
    state: "Karnataka",
    type: "Multi-Specialty Hospital",
    beds: 600,
    established: 1995,
    departments: 24,
  },
  {
    id: 6,
    name: "Manipal Heart Institute",
    city: "Bengaluru",
    state: "Karnataka",
    type: "Specialized Hospital",
    beds: 280,
    established: 2001,
    departments: 12,
  },
  {
    id: 7,
    name: "Lilavati Hospital",
    city: "Mumbai",
    state: "Maharashtra",
    type: "Multi-Specialty Hospital",
    beds: 500,
    established: 1978,
    departments: 20,
  },
  {
    id: 8,
    name: "Fortis General Hospital",
    city: "Mumbai",
    state: "Maharashtra",
    type: "General Hospital",
    beds: 340,
    established: 2003,
    departments: 15,
  },
  {
    id: 9,
    name: "AIIMS Delhi",
    city: "New Delhi",
    state: "Delhi",
    type: "Multi-Specialty Hospital",
    beds: 2500,
    established: 1956,
    departments: 40,
  },
  {
    id: 10,
    name: "Max Super Speciality Hospital",
    city: "New Delhi",
    state: "Delhi",
    type: "Multi-Specialty Hospital",
    beds: 500,
    established: 2002,
    departments: 22,
  },
  {
    id: 11,
    name: "Apollo Children's Hospital",
    city: "Chennai",
    state: "Tamil Nadu",
    type: "Specialized Hospital",
    beds: 200,
    established: 2008,
    departments: 14,
  },
  {
    id: 12,
    name: "Kauvery Hospital",
    city: "Chennai",
    state: "Tamil Nadu",
    type: "Multi-Specialty Hospital",
    beds: 400,
    established: 1999,
    departments: 17,
  },
];